routes:
  - path: /api/guest/signup
    method: POST
    controller: AuthController.SignUp
  - path: /api/guest/login
    method: POST
    controller: AuthController.Login
  - path: /api/user
    method: GET
    controller: UserController.GetUser
  - path: /api/user
    method: PUT
    controller: UserController.UpdateUser
  - path: /api/user
    method: DELETE
    controller: UserController.DeactivateUser
